<?php

namespace Spitchee\Entity\Repository;

use Doctrine\ORM\QueryBuilder;
use Spitchee\Entity\Conference;

/**
 * ConferenceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ConferenceRepository extends BaseRepository
{
    /**
     * @param array $args
     * @return QueryBuilder
     */
    public function getQueryBuilder($args = array())
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->select('c');

        $this->buildSearches('c', $args, $qb, 'uuid');

        return $qb;
    }

    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @return null|Conference
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    /**
     * @param mixed $id
     * @param null $lockMode
     * @param null $lockVersion
     * @return null|Conference
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }


}
