<?php

namespace Spitchee\Entity\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * SipAccountRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SipAccountRepository extends BaseRepository
{
    /**
     * @param array $args
     * @return QueryBuilder
     */
    public function getQueryBuilder($args = array())
    {
        $qb = $this->createQueryBuilder('sa')->select('sa');
        
        $this->buildSearches('sa', $args, $qb, 'id');
        
        $this->integrityCheck($args);
        
        return $qb;
    }
    
    public function findSipAccounts($args = array()) 
    {
        return $this->getQueryBuilder($args)->getQuery()->getResult();
    }
}
