Vagrant.configure(2) do |config|
  config.vm.box = "ARTACK/debian-jessie"
  config.vm.box_url = "https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie"
  #config.vm.synced_folder  "/Users/Nico/projets/spitchee/", "/home/vagrant/spitchee/",
  #  owner: "vagrant",
  #  group: "www-data",
  #  mount_options: ["dmode=777,fmode=777"]
  config.vm.synced_folder "./scripts/", "/tmp_scripts/"
  config.vm.synced_folder "./../../NAMI", "/spitchee_node/NAMI"
  config.vm.synced_folder "./../../SU", "/spitchee_node/SU"

  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 80, host: 8001
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 3002, host: 3002

  config.vm.provision :shell, :path => "scripts/vm_init.sh", :args => ["emacs"] #["emacs subversion"]
  config.vm.provision :shell, :path => "scripts/asterisk_init.sh"
  config.vm.provision :shell, :path => "scripts/node_init.sh"

  # On disable l'usb 2.0 sur VB pour cette instance car ca fait buger je sais pas pq
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
	  vb.customize ["modifyvm", :id, "--usbehci", "off"]
	end
end